# .github/workflows/publish.yml

name: Publish
on:
  push:
    tags: [ "**" ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Publish
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      
      - name: Publish
        run: deno publish --allow-slow-types